[package]
name = "md_fuse"
version = "0.0.2"
authors = ["Caio O Campos <caio.campos1204@gmail.com.br>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"


[lib]
crate-type = ["cdylib", "rlib"]
path = "./src/lib/mod.rs"
