name: Deploy

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Build
      run: cargo build --release

    - name: Create Release and Upload Binaries
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        make_latest: true
        files: target/release/md_fuse
